baseurl = "http://nebula-graph.io"
title = "Nebula Graph  - An Open Source, Distributed and High Performant Graph Database"
description = "Featuring horizontal scalability, strong data consistency, high availability, and SQL-like query language, Nebula Graph database enables you to get insight out of your connected data. Get it now. For free"
theme = "creative"
googleAnalytics = ""
DefaultContentLanguage = "default"  ###judge browser language 
defaultContentLanguageInSubdir = false

[languages]
################ init language Config ################
  [languages.default]
    contentDir = "content/default"

################ English Config ################
  [languages.en]
    contentDir = "content/en"
    [languages.en.params]

      # You can use Markdown syntax for urls [text](//url.to/source) for
      # most longer texts.

      # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
      # for more icons. The icons are represented by their corresponding
      # CSS class.

      # All projects of the portfolio are defined in their own files.
      # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
      # folder into the 'data' directory at the root of this Hugo site.
      # For more information take a look at the README.

      # To provide some metadata for search engines feel free to add some
      # information about you and your website.
      name = "Your name"

      # The path must be relative to the static folder
      favicon = "favicon.ico"


      # Navigation
      [languages.en.params.navigation]
        brand = "NebulaGraph"

        [[languages.en.params.navigation.links]]
          title = "Home"
          link = "/"
        [[languages.en.params.navigation.links]]
          title = "Solutions"
          [[languages.en.params.navigation.links.links]]
            title = "Why Nebula Graph"
            link = "/en/#advantage"
          [[languages.en.params.navigation.links.links]]
            title = "Get Started"
            link = "https://docs.nebula-graph.io/manual-EN/1.overview/2.quick-start/1.get-started/#batch-inserting"
            target = "_blank"
          # [[languages.en.params.navigation.links.links]]
          # 	title = "Use cases"
        # [[languages.en.params.navigation.links]]
        # 	title = "Customers"
        [[languages.en.params.navigation.links]]
          title = "Resources"
          [[languages.en.params.navigation.links.links]]
            title = "Blog"
            link = "/en/posts"
          [[languages.en.params.navigation.links.links]]
            title = "Docs"
            link = "https://docs.nebula-graph.io/"
        [[languages.en.params.navigation.links]]
          title = "Forum"
          link = "https://discuss.nebula-graph.io/"
          target = "_blank"
        [[languages.en.params.navigation.links]]
          icon = "glyphicon glyphicon-globe"
            [[languages.en.params.navigation.links.links]]
              title = "English"
              link = "/en"
            [[languages.en.params.navigation.links.links]]
              title = "中文"
              link = "/cn"

      # Hero section
      [languages.en.params.header]
        # To change the background of the header section, replace the 'header.jpg' at './static/img' with your own.
        slogan     = "Nebula Graph"
        subtitle   = "A truly distributed, linear scalable, lighting-fast graph database."
        buttonText = "Get Started"

      # Footer section
      [languages.en.params.footer]
        [languages.en.params.footer.social]
          title = "Follow us on"
          [[languages.en.params.footer.social.links]]
              title = "Twitter"
              class = "icon fa fa-twitter"
              link = "https://twitter.com/NebulaGraph"
              target = "_blank"
          [[languages.en.params.footer.social.links]]
              title = "WeiBo"
              class = "icon fa fa-weibo"
              link = "https://weibo.com/nebulagraph"
              target = "_blank"
          [[languages.en.params.footer.social.links]]
              title = "LinkedIn"
              class = "icon fa fa-linkedin"
              link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
              target = "_blank"
          [[languages.en.params.footer.social.links]]
              title = "YouTube"
              class = "icon fa fa-youtube"
              link = "https://www.youtube.com/channel/UC73V8q795eSEMxDX4Pvdwmw"
              target = "_blank"
          [[languages.en.params.footer.social.links]]
              title = "FaceBook"
              class = "icon fa fa-facebook"
              link = "https://www.facebook.com/NebulaGraph/"
              target = "_blank"
          [[languages.en.params.footer.social.links]]
              title = "WeChat"
              class = "icon fa fa-wechat"
              id = "#myModal"
              target = "_blank"
        [[languages.en.params.footer.community]]
          title = "Community"
          [[languages.en.params.footer.community.links]]
              title = "GitHub"
              link = "https://github.com/vesoft-inc/nebula"
              target = "_blank"
          [[languages.en.params.footer.community.links]]
              title = "Forum"
              link = "https://discuss.nebula-graph.io/"
              target = "_blank"
          [[languages.en.params.footer.community.links]]
              title = "Slack"
              link = "https://join.slack.com/t/nebulagraph/shared_invite/enQtNjIzMjQ5MzE2OTQ2LTM0MjY0MWFlODg3ZTNjMjg3YWU5ZGY2NDM5MDhmOGU2OWI5ZWZjZDUwNTExMGIxZTk2ZmQxY2Q2MzM1OWJhMmY#"
              target = "_blank"
        [[languages.en.params.footer.company]]
          title = "Company"
          [[languages.en.params.footer.company.links]]
              title = "About"
              link = "https://github.com/vesoft-inc/nebula"
              target = "_blank"
          [[languages.en.params.footer.company.links]]
              title = "News"
              link = "https://weibo.com/nebulagraph"
              target = "_blank"
          [[languages.en.params.footer.company.links]]
              title = "Contact"
              link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
              target = "_blank"
          [[languages.en.params.footer.company.links]]
              title = "Career"
              link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
              target = "_blank"
        

      # [languages.en.params.advantage]
      #   headline    = "Why Nebula"
      #   description = "blablablabla..."
      #   buttonText  = "Get started!"


      # Service section
      [languages.en.params.features]
        headline = "Nebula Graph Features"

          [[languages.en.params.features.list]]
            pic = "feature1.png"
            title = "Open Source"
            description = "We are looking forward to collaborating with the community to popularize and promote the graph database."

          [[languages.en.params.features.list]]
            pic = "feature2.png"
            title = "High Performance"
            description = "Nebula Graph provides low latency read and write, while still maintaining high throughput."

          [[languages.en.params.features.list]]
            pic = "feature3.png"
            title = "SQL-like"
            description = "Nebula Graph's SQL-like query language is easy to understand and powerful enough to meet complex business needs."

          [[languages.en.params.features.list]]
            pic = "feature4.png"
            title = "Secure"
            description = "With role-based access control, Nebula Graph only allows authenticated access."

          [[languages.en.params.features.list]]
            pic = "feature5.png"
            title = "Scalable"
            description = "With shared-nothing distributed architecture, Nebula Graph offers linear scalability."

          [[languages.en.params.features.list]]
            pic = "feature6.png"
            title = "Extensible"
            description = "Nebula Graph supports multiple storage engine types. The query language can be extended to support new algorithms."

          [[languages.en.params.features.list]]
            pic = "feature7.png"
            title = "Transactional"
            description = "With distributed ACID transaction support, Nebula Graph ensures data integrity."

          [[languages.en.params.features.list]]
            pic = "feature8.png"
            title = "Highly Available"
            description = "Nebula Graph guarantees high availability even in case of failures."

      # [languages.en.params.portfolio.modal]
      #       client = "Client"
      #       date = "Date"
      #       category = "Category"
      #       buttonText = "Close"

      # Contact section
      [languages.en.params.contact]
        headline = "Let's Get In Touch!"
        description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
        phone = "123-456-6789"
        email = "feedback@startbootstrap.com"
			# blog section
      [languages.en.params.blog]
        title = "Contents"
        

################ 中文配置 ################
  [languages.cn]
    contentDir = "content/cn"
    [languages.cn.params]

      # You can use Markdown syntax for urls [text](//url.to/source) for
      # most longer texts.

      # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
      # for more icons. The icons are represented by their corresponding
      # CSS class.

      # All projects of the portfolio are defined in their own files.
      # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
      # folder into the 'data' directory at the root of this Hugo site.
      # For more information take a look at the README.

      # To provide some metadata for search engines feel free to add some
      # information about you and your website.
      name = "Your name"

      # The path must be relative to the static folder
      favicon = "favicon.ico"


      # Navigation
      [languages.cn.params.navigation]
        brand = "NebulaGraph"

        [[languages.cn.params.navigation.links]]
          title = "首页"
          link = "/"
        [[languages.cn.params.navigation.links]]
          title = "了解"
          # [[languages.cn.params.navigation.links.links]]
          #   title = "Nebula Graph"
          #   link = "/#advantage"
          [[languages.cn.params.navigation.links.links]]
            title = "开始尝试"
            link = "https://docs.nebula-graph.io/manual-EN/1.overview/2.quick-start/1.get-started/#batch-inserting"
            target = "_blank"
          # [[languages.cn.params.navigation.links.links]]
          # 	title = "Use cases"
        # [[languages.cn.params.navigation.links]]
        # 	title = "Customers"
        [[languages.cn.params.navigation.links]]
          title = "资讯"
          [[languages.cn.params.navigation.links.links]]
            title = "博客"
            link = "/cn/posts"
          [[languages.cn.params.navigation.links.links]]
            title = "文档"
            link = "https://docs.nebula-graph.io/"
        [[languages.cn.params.navigation.links]]
          title = "论坛"
          link = "https://discuss.nebula-graph.io/"
          target = "_blank"
        [[languages.cn.params.navigation.links]]
          icon = "glyphicon glyphicon-globe"
            [[languages.cn.params.navigation.links.links]]
              title = "English"
              link = "/en"
            [[languages.cn.params.navigation.links.links]]
              title = "中文"
              link = "/cn"

      # Hero section
      [languages.cn.params.header]
        # To change the background of the header section, replace the 'header.jpg' at './static/img' with your own.
        slogan     = "Nebula Graph"
        subtitle   = "一个可靠的分布式，线性扩容，性能高效的图数据库"
        buttonText = "开始尝试"

      # Footer section
      [languages.cn.params.footer]
        [languages.cn.params.footer.social]
          title = "关注我们"
          [[languages.cn.params.footer.social.links]]
              title = "Twitter"
              class = "icon fa fa-twitter"
              link = "https://twitter.com/NebulaGraph"
              target = "_blank"
          [[languages.cn.params.footer.social.links]]
              title = "微博"
              class = "icon fa fa-weibo"
              link = "https://weibo.com/nebulagraph"
              target = "_blank"
          [[languages.cn.params.footer.social.links]]
              title = "LinkedIn"
              class = "icon fa fa-linkedin"
              link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
              target = "_blank"
          [[languages.cn.params.footer.social.links]]
              title = "YouTube"
              class = "icon fa fa-youtube"
              link = "https://www.youtube.com/channel/UC73V8q795eSEMxDX4Pvdwmw"
              target = "_blank"
          [[languages.cn.params.footer.social.links]]
              title = "FaceBook"
              class = "icon fa fa-facebook"
              link = "https://www.facebook.com/NebulaGraph/"
              target = "_blank"
          [[languages.cn.params.footer.social.links]]
              title = "微信"
              class = "icon fa fa-wechat"
              modal = "btn-lg"
              id = "#myModal"
              target = "_blank"
        [[languages.cn.params.footer.community]]
          title = "社区"
          [[languages.cn.params.footer.community.links]]
              title = "GitHub"
              link = "https://github.com/vesoft-inc/nebula"
              target = "_blank"
          [[languages.cn.params.footer.community.links]]
              title = "论坛"
              link = "https://discuss.nebula-graph.io/"
              target = "_blank"
          [[languages.cn.params.footer.community.links]]
              title = "Slack"
              link = "https://join.slack.com/t/nebulagraph/shared_invite/enQtNjIzMjQ5MzE2OTQ2LTM0MjY0MWFlODg3ZTNjMjg3YWU5ZGY2NDM5MDhmOGU2OWI5ZWZjZDUwNTExMGIxZTk2ZmQxY2Q2MzM1OWJhMmY#"
              target = "_blank"
        [[languages.cn.params.footer.company]]
          title = "公司"
          [[languages.cn.params.footer.company.links]]
              title = "关于"
              link = "https://github.com/vesoft-inc/nebula"
              target = "_blank"
          [[languages.cn.params.footer.company.links]]
              title = "新闻"
              link = "https://weibo.com/nebulagraph"
              target = "_blank"
          [[languages.cn.params.footer.company.links]]
              title = "联系"
              link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
              target = "_blank"
          [[languages.cn.params.footer.company.links]]
              title = "招聘"
              link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
              target = "_blank"
        

      # About section
      # [languages.cn.params.advantage]
      #   headline    = "Why Nebula"
      #   description = "blablablabla..."
      #   buttonText  = "Get started!"


      # Service section
      [languages.cn.params.features]
        headline = "Nebula Graph 特性"

          [[languages.cn.params.features.list]]
            pic = "feature1.png"
            title = "开源"
            description = "我们致力于与社区合作普及及促进图数据库的发展。"

          [[languages.cn.params.features.list]]
            pic = "feature2.png"
            title = "高性能"
            description = "Nebula Graph 在维持高吞吐量的同时依旧能做到低时延的读写。"

          [[languages.cn.params.features.list]]
            pic = "feature3.png"
            title = "类SQL查询"
            description = "Nebula Graph的类 SQL 查询语言不仅易于理解，同时能满足各类复杂业务需求。"

          [[languages.cn.params.features.list]]
            pic = "feature4.png"
            title = "安全"
            description = "具有基于角色的权限控制，授权才能访问。"

          [[languages.cn.params.features.list]]
            pic = "feature5.png"
            title = "扩容"
            description = "基于shared-nothing 分布式架构，Nebula Graph 支持线性扩容。"

          [[languages.cn.params.features.list]]
            pic = "feature6.png"
            title = "扩展性"
            description = "Nebula Graph 支持多种类型存储引擎。查询语言也可以拓展支持新的算法。"
 
          [[languages.cn.params.features.list]]
            pic = "feature7.png"
            title = "事务性"
            description = "采用分布式 ACID 事务支持，以确保数据完整性。"

          [[languages.cn.params.features.list]]
            pic = "feature8.png"
            title = "高可用"
            description = "Nebula Graph 保证在局部失败的情况下服务的高可用性。"

      # [languages.cn.params.portfolio.modal]
      #       client = "Client"
      #       date = "Date"
      #       category = "Category"
      #       buttonText = "Close"
			# blog section
			[languages.cn.params.blog]
						title = "目录"